FROM python:3.10.13-alpine

COPY . /app

WORKDIR /app

RUN python3 -m pip install -r requirements.txt

ENV API_KEY="AIzaSyCUxMiitzSTQhal-znPdoa8DR6cNp6Xk_w"

RUN pip install Flask tensorflow

EXPOSE 80

CMD ["python", "server.py"]